### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by nonnymoose** [cymonsgames/ASCIIpOrtal#14]
I just wanted to let @cymonsgames  know that http://cymonsgames.com/asciiportal is down.
```
$ ping http://cymonsgames.com/asciiportal
ping: unknown host http://cymonsgames.com/asciiportal
```

**Comment by cymonsgames** [comment]
Yes. The site wasn't getting enough traffic to merit the expense of maintaining it, so it's hosting was dropped. I've still got the archives, but I'm more into 3D printing these days.

AsciiPortal, however, can be found on various other sites online including here and moddb.

**Comment by nonnymoose** [comment]
Great! I just wanted to make sure you knew! :)

**Comment by henk23** [comment]
Could make sense to remove the link from the readme and the short description on GitHub ^^ People will click on it

**Comment by PowerUser64** [comment]
Could it be replaced with a link to archive.org instead?

Here's the most recent archive of it that I found:
https://web.archive.org/web/20140330182218/http://cymonsgames.com/asciiportal/
