### ISSUE TITLE
ASCIIpOrtal compiles with old, buggy release of yaml-cpp

### ISSUE THREAD

**Issue by nonnymoose** [cymonsgames/ASCIIpOrtal#15]
[jbeder/yaml-cpp](https://github.com/jbeder/yaml-cpp/) version 0.2.6 has a [bug](https://github.com/jbeder/yaml-cpp/issues/112) that produces the following error when compiled with `gcc-4.6`: 

```
In file included from /usr/local/src/ASCIIpOrtal-1.3-beta8/yaml-cpp/src/nodeownership.h:10:0,
                 from /usr/local/src/ASCIIpOrtal-1.3-beta8/yaml-cpp/src/nodeownership.cpp:1:
/usr/local/src/ASCIIpOrtal-1.3-beta8/yaml-cpp/src/ptr_vector.h: In member function void YAML::ptr_vector<T>::push_back(std::auto_ptr<T>):
/usr/local/src/ASCIIpOrtal-1.3-beta8/yaml-cpp/src/ptr_vector.h:31:21: error: NULL was not declared in this scope
    m_data.push_back(NULL);
```

This could be fixed by adding an `#include <cstddef>` to ptr_stack.h and 
ptr_vector.h, and making again.

However, I would suggest updating to a newer release of yaml-cpp.

**Comment by zorun** [comment]
Note that the default Makefile target builds yaml-cpp locally, but that's not the recommanded option (run `make linux` to use the system version).

Anyway, should now be fixed.
