### ISSUE TITLE
Binary downloads missing?

### ISSUE THREAD

**Issue by Nikitaw99** [cymonsgames/ASCIIpOrtal#16]
I am stuck. I really want to play the game, however I cannot find any binaries and cannot compile it myself (I don't know how to, exactly).

I am using `Windows 7`.

**Comment by cymonsgames** [comment]
IF all you want to do is play the game it's best to get the archive on moddb. http://www.moddb.com/games/asciiportal

**Comment by Nikitaw99** [comment]
Thank you!
